basic/urls.py
from django.urls import path
from . import views
from basic.views import *

app_name = 'basic'

urlpatterns = [
    path('',HomeView.as_view(),name='home'),
    # path('search/',SearchView.as_view(),name='search-results'),
    path('search/',views.search_view,name='search-results'),
    
    path('index/',IndexView.as_view(),name='index'),
    # path('index/main/',MainView.as_view(),name='main'),
    path('index/main/',views.main_UniVar,name='main'),


]

m3di/urls.py
from django.urls import path
from . import views
from m3di.views import *

app_name = 'm3di'

urlpatterns = [    
    path('',IndexView.as_view(),name='index'),
    path('main/',views.main_UniVar,name='main'),
    path('help/',HelpView.as_view(), name='help'),
    path('statistics/',StatisticsView.as_view(), name='statistics'),
    path('contact/',ContactView.as_view(), name='contact'),
    path('doc/',DocView.as_view(), name='doc')
]

m3di_front/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('m3di/',include('m3di.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

basic/views.py
from django.shortcuts import render
from django.views import generic
from .models import *
from itertools import chain

# Create your views here.


class HomeView(generic.TemplateView):
    template_name = 'basic/home.html'


class IndexView(generic.TemplateView):
    template_name = 'basic/index.html'

# class SearchView(generic.ListView):
#     template_name = 'basic/search.html'

#     def get_queryset(self): #overwrite the get_queryset method
#         query = self.request.GET.get('q', None)

#         if query is not None:
#             proname_results = Pronameunique.objects.filter(uniprot_id__icontains=query)
#             sigpep_results = Sigpep.objects.filter(sp_uniprot_id__icontains=query)
#             basicinfo_results = Basicbackup.objects.filter(uniprot_id__icontains=query)

#             # combine querysets
#             queryset_chain = chain(
#                 proname_results,
#                 sigpep_results,
#                 basicinfo_results
#             )

#             return queryset_chain
#         return ProNameUnique.objects.none()
# testinggit123


# class SearchView(generic.ListView):
#     template_name = 'basic/search.html'

#     def get_queryset(self):  # overwrite the get_queryset method
#         query = self.request.GET.get('q', None)

#         if query is not None:
#             basic_results = Basicinfo2.objects.raw(
#                 'SELECT * FROM BasicInfo2 LEFT JOIN SignalPeptide ON uniprot_id=sp_uniprot_id WHERE uniprot_id = %s', [query])

#             return basic_results
#         return Basicinfo2.objects.none()

def search_view(request):
    if request.method == "GET":
        query_uni = request.GET['q']
        query_var = request.GET['v']

        results_basic = Basicinfo2.objects.raw(
            'SELECT * FROM BasicInfo2 LEFT JOIN SignalPeptide ON uniprot_id=sp_uniprot_id WHERE uniprot_id = %s', [
                query_uni]
        )
        results_topo = Topodom.objects.raw(
            'SELECT id, topology FROM (SELECT * FROM TopoDom WHERE uniprot = %s) AS tab WHERE topo_start <= %s and topo_end >= %s', [
                query_uni, query_var, query_var]
        )
        results_variant = MissenseVarCom.objects.raw(
            'SELECT * FROM Missense_Var_Com WHERE uniprot = %s and posuniprot = %s', [
                query_uni, query_var]
        )
        context = {
            'results_basic': results_basic,
            'results_topo': results_topo,
            'results_variant': results_variant}

        return render(request, 'basic/search.html', context)

# class MainView(generic.ListView):
#     template_name = 'basic/main.html'

#     def get_queryset(self):  # overwrite the get_queryset method
#         query_uniprot = self.request.GET.get('q', None)
#         query_residue = self.request.GET.get('q2', None)

#         if query_uniprot is not None:
#             basic_results = Basicinfo2.objects.raw(
#                 'SELECT * FROM BasicInfo2 LEFT JOIN SignalPeptide ON uniprot_id=sp_uniprot_id WHERE uniprot_id = %s', [query_uniprot])

#             return basic_results
#         return Basicinfo2.objects.none()


def main_UniVar(request):
    if request.method == "GET":
        query_uni = request.GET['q']
        query_var = request.GET['v']

        results_protein = Pronameunique.objects.raw(
            'SELECT * FROM ProNameUnique join ProteinLink on ProNameUnique.uniprot_id = ProteinLink.uniprot_id where ProNameUnique.uniprot_id = %s' , [query_uni]
        )

        results_gene = Geneinfo.objects.raw(
            'SELECT * from GeneInfo where uniprot_id = %s', [query_uni]
        )

        results_loc_cellcomp = Topocellcomp.objects.raw( 
            'SELECT * from TopoCellComp where uniprot_id = %s', [query_uni]
        )

        results_loc_topolabel = Topocellcomp.objects.raw(
            'SELECT * FROM TopoCellComp where uniprot_id = %s AND topo_label IS NOT NULL', [query_uni]
        )

        results_signal = Signalpeptide.objects.raw(
            'SELECT * FROM SignalPeptide where sp_uniprot_id = %s', [query_uni]
        )

        Pfam_results_general = Pfam.objects.raw(
            'SELECT * FROM Pfam WHERE  pf_uniprot_id = %s ', [query_uni]
        )
        
        function_results = Proteinfunctionl.objects.raw(
            'SELECT * FROM ProteinFunctionL where uniprot_id = %s', [query_uni]
        )

        tm_results = Transmem.objects.raw(
            'SELECT * from TransMem join EviCodes on TransMem.eco = EviCodes.eco where tm_uniprot_id = %s order by tm_start', [query_uni]
        )

        topo1_results = Topodom.objects.raw(
            'select * from TopoDom join EviCodes on TopoDom.eco = EviCodes.eco where uniprot = %s order by topo_start', [query_uni]
        )

        bind1_results = Bindsite.objects.raw(
            'select * from BindSite  join EviCodes on BindSite.eco = EviCodes.eco where uniprot_id = %s order by bs_position', [query_uni]
        )

        ptm1_results = Ptms.objects.raw(
            'select * from PTMs join EviCodes on PTMs.eco = EviCodes.eco where ptm_uniprot_id = %s ' , [query_uni]
        )

        var_results =  MissenseVarCom.objects.raw(
            'SELECT * FROM Missense_Var_Com WHERE uniprot = %s ' , [query_uni]
            )
    

        if query_uni and query_var is not None : 

            results_signal_var = Signalpeptide.objects.raw(
            'SELECT * FROM SignalPeptide where sp_uniprot_id = %s and signal_peptide > %s ', [query_uni, query_var]
            )   

            trans_dom_var = Transmem.objects.raw(
            'SELECT * FROM TransMem where tm_start <= %s AND tm_end >= %s AND tm_uniprot_id = %s ', [query_var, query_var, query_uni]
            )
        
            results_binding = Bindsite.objects.raw( 
            'SELECT * from BindSite join EviCodes on BindSite.eco = EviCodes.eco where uniprot_id = %s and bs_position = %s ', [query_uni, query_var]
            )

            results_topo = Topodom.objects.raw(
            '''SELECT id, topology FROM (SELECT * FROM TopoDom WHERE uniprot = %s) AS tab 
            WHERE topo_start <= %s and topo_end >= %s''', [
                query_uni, query_var, query_var]
            )
            results_variant = MissenseVarCom.objects.raw(
            'SELECT * FROM Missense_Var_Com WHERE uniprot = %s AND  posuniprot = %s' , [query_uni, query_var]
            )
            
            results_PTM = Ptms.objects.raw(
            'SELECT * FROM PTMs WHERE ptm_uniprot_id = %s AND pos = %s ' , [query_uni, query_var]
            )

            results_sequence = SeqCanonical.objects.raw( 
            'SELECT * FROM (SELECT id,  SUBSTRING(sequence, %s, 1) AS sub  FROM Seq_canonical where uniprot_id = %s) AS wt JOIN aa_conversion on wt.sub = aa_conversion.one_let' , [query_var, query_uni]
            )

            Pfam_results = Pfam.objects.raw(
            'SELECT * FROM Pfam WHERE env_s  <= %s AND env_e >= %s AND pf_uniprot_id = %s ', [query_var, query_var, query_uni]
            )

        elif query_uni :

            results_variant = MissenseVarCom.objects.raw(
                'SELECT * FROM Missense_Var_Com WHERE uniprot = %s', [
                    query_uni]
            )

        results_interact = Stringinteractions.objects.raw(
            '''SELECT id, s.string_p1, a.uniprot_id as uniprot_p1, s.string_p2, b.uniprot_id as uniprot_p2, experimental, data_base, combined_score, Json_object('uniprot_p1', a.uniprot_id, 'uniprot_p2',  b.uniprot_id) AS col_json
                FROM StringInteractions as s
                LEFT JOIN StringToUniprot as a
                ON a.string_id = s.string_p1
                LEFT JOIN StringToUniprot as b
                ON b.string_id = s.string_p2
                WHERE a.uniprot_id = %s
                AND b.uniprot_id IS NOT NULL AND experimental > 0
                ORDER BY s.combined_score
                limit 10;''', [query_uni]
        )

        results_interact_additional = Stringinteractions.objects.raw(
            '''WITH t as (SELECT b.uniprot_id as uniprot_p2
                FROM StringInteractions as s
                LEFT JOIN StringToUniprot as a
                ON a.string_id = s.string_p1
                LEFT JOIN StringToUniprot as b
                ON b.string_id = s.string_p2
                WHERE a.uniprot_id = %s
                AND b.uniprot_id IS NOT NULL
                AND experimental > 0
                ORDER BY s.combined_score
                limit 10)
                SELECT id, u.string_p1, c.uniprot_id as uniprot_p1, u.string_p2, d.uniprot_id as uniprot_p2, u.experimental, u.data_base, u.combined_score, 
                Json_object('uniprot_p1', c.uniprot_id, 'uniprot_p2',  d.uniprot_id) AS col_json_additional
                FROM StringInteractions as u
                LEFT JOIN StringToUniprot as c
                ON c.string_id = u.string_p1
                LEFT JOIN StringToUniprot as d
                ON d.string_id = u.string_p2
                WHERE c.uniprot_id in (select * from t) AND d.uniprot_id in (select * from t);''', [query_uni]
        )

        results_interact_list = []
        for item in results_interact:
            results_interact_list.append(item.col_json)
        for item in results_interact_additional:
            results_interact_list.append(item.col_json_additional)
        results_interact_string = '{"interactors": [' + \
            ",".join(results_interact_list) + ']}'
        

        context = {
            'query_uni': query_uni,
            'query_var': query_var,
            'results_protein' : results_protein, 
            'results_gene': results_gene, 
            'results_signal' : results_signal,
            'results_signal_var' : results_signal_var,
            'trans_dom_var' : trans_dom_var,
            'tm_results' : tm_results, 
            'results_topo': results_topo,
            'results_loc_cellcomp' : results_loc_cellcomp, 
            'results_loc_topolabel': results_loc_topolabel,

basic/templates/basic/index.html
{% load static %}

<!DOCTYPE html>

<html>
  <head> 
      <title>M3DI | Home</title>
      <meta name="description" content="Welcome to Missense3D-Interaction">
      <!--Font Awesome kit's code-->
      <script src="https://kit.fontawesome.com/777bbb3675.js" crossorigin="anonymous"></script>
      <!--Link CSS stylesheet-->
      <link rel="stylesheet" href="{% static 'basic/styles.css' %}" />
  </head>

  <body>

    <div id="stick-to-top">
      <div class="top_bar">
        <div class="container"></div>
      </div>
      <header class="main-header">
        <div class="container">
          <a id="m3di_logo_left" href="{% url 'basic:index' %}">
            <img src="{% static 'basic/images/logo.png' %}" width="150" height="70" ></a>
          <nav class="nav main-nav">            
            <ul>
              <li><a href="{% url 'basic:index' %}">Home</a></li>
              <li><a href="about.html">About</a></li>
              <li><a href="dataset.html">Dataset</a></li>
              <li><a href="contact.html">Contact us</a></li>
            </ul>
          </nav>
        </div>      
      </header>
    </div>
    
    
    <section class="hero">
        <div class="container">
          <h1 id="welcome"> Welcome to M3DI </h1>
          <p>
             M3DI is a database integrating data from UniProt, Missense3D , String and Interactome-3D to provide the user with a tool to analyse the impact of missense variants on protein-protein interactions. 
          </p>
          <br>
          <a href="#home-search">
          
        </div>
    </section>

    <section id="home-search" class="home-search">
        <div class="container">

        <form action="{% url 'basic:main' %}" method="get">
          <table>
            <tr>
              <td></td>
              <td class="left" id="example">
                <a href="#home-search" onclick="populate_uniprot()">Example: Q9BYF1, 199</a>
              </td>
            </tr>
              <tr>
                <td class="right"><label>Uniprot ID/Gene ID:</label></td>
                <td class="left">
                  <input id="input_uni" name="q" type="text" placeholder="e.g. Q9BYF1 or ACE2" size="21px">
                  <i class="fa-solid fa-circle-info"></i>
                </td>
              </tr>
            <tr>
              <td class="right"><label>Residue Position:</label></td>
              <td class="left">
                <input id="input_var" name="v" type="text" placeholder="e.g. 199"  size="14px">
              </td>
            </tr>
            <!-- <tr>
              <td class="right"><label>Mutation:</label></td>
              <td class="left">
                <input id="input_wt" name="wt" type="text" placeholder="e.g. TYR" size="8px">
                <i class="fa-solid fa-arrow-right"></i>
                <input id="input_mut" name="mut" type="text" placeholder="e.g. HIS" size="8px">
              </td>
            </tr> -->
            <tr>
              <td></td>
              <td class="left">
                <a href="{% url 'basic:main' %}">
                  <button type="submit">Start your search</button></a>
              </td>
            </tr>
          </table>
        </form>


      </div>
    </section>

     

    <section class="home-detail">
      <div class="container">
      </div>
    </section>

    <!-- <hr color="#CAC4D7"> -->
    
    <footer2>
      <div class="container">
        <span id="msc_left">MSc Bioinformatics and Systems Biology</span>
        <img id="ic_logo_right" src="{% static 'basic/images/Imperial.png' %}" width="400">
      </div>
    </footer2>



    <script src="{% static 'basic/scripts.js' %}"></script>

  </body>
</html>