m3di/urls.py
from django.urls import path
from . import views
from m3di.views import *

app_name = 'm3di'

urlpatterns = [    
    path('',IndexView.as_view(),name='index'),
    path('main/',views.main_UniVar,name='main'),
    path('help/',HelpView.as_view(), name='help'),
    path('statistics/',StatisticsView.as_view(), name='statistics'),
    path('contact/',ContactView.as_view(), name='contact'),
    path('doc/',DocView.as_view(), name='doc')
]

m3di_front/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('m3di/',include('m3di.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

m3di/views.py
from django.shortcuts import render
from django.views import generic
from .models import *
import json


# Convert RawQuerySet to string in json format for javascript parsing

def raw_to_json(*RawQuerySets):
    array = []
    for set in RawQuerySets:
        for item in set:
            array.append({field:getattr(item,field) for field in set.columns})
    return json.dumps(array)


# Create Views

class IndexView(generic.TemplateView):
    template_name = 'm3di/index.html'

class DocView(generic.TemplateView):
    template_name = 'm3di/doc.html'

class StatsView(generic.TemplateView):
    template_name = 'm3di/stats.html'

class ContactView(generic.TemplateView):
    template_name = 'm3di/contact.html'

def main_UniVar(request):
    if request.method == "GET":
        # Obtain UniProt or gene ID
        query = request.GET['q']
        # Obtain residue position of variant        
        query_var = request.GET['v']
        # Obtain interaction score threshold
        if request.GET['s'] != 'Custom':
            query_sco = request.GET['s']
        else:
            query_sco = request.GET['s_custom']
        # Obtain max number of iteractors
        if request.GET['l'] != 'Custom':
            query_lim = request.GET['l']
        else:
            query_lim = request.GET['l_custom']

    if query:
        # Allow both UniProt and Gene ID input
        results_basic = Basicinfo2.objects.raw('SELECT * FROM BasicInfo2 WHERE uniprot_id=%s OR gene_name=%s', [query,query])
        # Convert query to UniProtID only
        query_uni = results_basic[0].uniprot_id

        results_protein = Pronameunique.objects.raw(
            'SELECT * FROM ProNameUnique join ProteinLink on ProNameUnique.uniprot_id = ProteinLink.uniprot_id where ProNameUnique.uniprot_id = %s' , [query_uni]
        )

        results_gene = Geneinfo.objects.raw(
            'SELECT * from GeneInfo where uniprot_id = %s', [query_uni]
        )

        results_loc_cellcomp = Topocellcomp.objects.raw( 
            'SELECT * from TopoCellComp where uniprot_id = %s', [query_uni]
        )

        results_loc_topolabel = Topocellcomp.objects.raw(
            'SELECT * FROM TopoCellComp where uniprot_id = %s AND topo_label IS NOT NULL', [query_uni]
        )

        results_signal = Signalpeptide.objects.raw(
            'SELECT * FROM SignalPeptide where uniprot_id = %s', [query_uni]
        )

        Pfam_results_general = Pfam.objects.raw(
            'SELECT * FROM Pfam WHERE  uniprot_id = %s ', [query_uni]
        )
        
        function_results = Proteinfunctionl.objects.raw(
            'SELECT * FROM ProteinFunctionl where uniprot_id = %s', [query_uni]
        )

        tm_results = Transmem.objects.raw(
            'SELECT * from TransMem join EviCodes on TransMem.eco = EviCodes.eco where uniprot_id = %s order by tm_start', [query_uni]
        )

        topo1_results = Topodom.objects.raw(
            'select * from TopoDom join EviCodes on TopoDom.eco = EviCodes.eco where uniprot_id = %s order by topo_start', [query_uni]
        )

        bind1_results = Bindsite.objects.raw(
            'select * from BindSite  join EviCodes on BindSite.eco = EviCodes.eco where uniprot_id = %s order by bs_position', [query_uni]
        )

        ptm1_results = Ptms.objects.raw(
            'select * from PTMs join EviCodes on PTMs.eco = EviCodes.eco where uniprot_id = %s ' , [query_uni]
        )

        var_results =  Missensevarcom.objects.raw(
            'SELECT * FROM MissenseVarCom WHERE uniprot_id = %s ' , [query_uni]
            )
    

        if query_uni and query_var is not None : 

            results_signal_var = Signalpeptide.objects.raw(
            'SELECT * FROM SignalPeptide where uniprot_id = %s and signal_peptide > %s ', [query_uni, query_var]
            )   

            trans_dom_var = Transmem.objects.raw(
            'SELECT * FROM TransMem where tm_start <= %s AND tm_end >= %s AND uniprot_id = %s ', [query_var, query_var, query_uni]
            )
        
            results_binding = Bindsite.objects.raw( 
            'SELECT * from BindSite join EviCodes on BindSite.eco = EviCodes.eco where uniprot_id = %s and bs_position = %s ', [query_uni, query_var]
            )

            results_topo = Topodom.objects.raw(
            '''SELECT id, topology FROM (SELECT * FROM TopoDom WHERE uniprot_id = %s) AS tab 
            WHERE topo_start <= %s and topo_end >= %s''', [
                query_uni, query_var, query_var]
            )
            results_variant = Missensevarcom.objects.raw(
            'SELECT * FROM MissenseVarCom WHERE uniprot_id = %s AND  posuniprot = %s' , [query_uni, query_var]
            )
            
            results_PTM = Ptms.objects.raw(
            'SELECT * FROM PTMs WHERE uniprot_id = %s AND pos = %s ' , [query_uni, query_var]
            )

            results_sequence = Seqcanonical.objects.raw( 
            'SELECT * FROM (SELECT id,  SUBSTRING(sequence, %s, 1) AS sub  FROM SeqCanonical where uniprot_id = %s) AS wt JOIN aa_conversion on wt.sub = aa_conversion.one_let' , [query_var, query_uni]
            )

            Pfam_results = Pfam.objects.raw(
            'SELECT * FROM Pfam WHERE ali_s  <= %s AND ali_e >= %s AND uniprot_id = %s ', [query_var, query_var, query_uni]
            )

        elif query_uni :

            results_variant = Missensevarcom.objects.raw(
                'SELECT * FROM MissenseVarCom WHERE uniprot_id = %s', [
                    query_uni]
            )


        # Return a list of nodes (interactors) for cytoscape
        cyNodes_raw = Stringinteractions.objects.raw('''
            SELECT * FROM BasicInfo2 WHERE uniprot_id = %s
            UNION
            (SELECT b.* FROM StringInteractions as s
            LEFT JOIN StringToUniprot as su1 ON su1.string_id = s.string_p1
            LEFT JOIN StringToUniprot as su2 ON su2.string_id = s.string_p2
            LEFT JOIN BasicInfo2 as b ON b.uniprot_id = su2.uniprot_id
            WHERE su1.uniprot_id = %s
                AND su2.uniprot_id IS NOT NULL 
                AND s.experimental >= %s
            ORDER BY s.experimental desc, s.combined_score, s.id 
            LIMIT %s);
            ''',[query_uni,query_uni,float(query_sco)*1000,int(query_lim)])

        # Use a list as an SQL parameter in Python:
        # Call tuple(list) to convert the list into a tuple object.
        # Call str.format(tuple) to format the SQL query str with the tuple from the previous step.
        nodes = tuple([obj.uniprot_id for obj in cyNodes_raw])

        # Avoid error caused by trailing comma in a single-item tuple (no interactors)
        if len(nodes) > 1:
            cyEdges_raw = Stringinteractions.objects.raw('''
                SELECT s.id, su1.uniprot_id AS p1, su2.uniprot_id AS p2,
                    s.experimental, i.type, i.PDB_id
                FROM StringInteractions as s
                LEFT JOIN StringToUniprot as su1 ON su1.string_id = s.string_p1
                LEFT JOIN StringToUniprot as su2 ON su2.string_id = s.string_p2
                LEFT JOIN Interactome3d as i ON i.prot1 = su2.uniprot_id 
                    AND i.prot2 = su1.uniprot_id      
                WHERE su1.uniprot_id in {} 
                    AND su2.uniprot_id in {}
                    AND su1.uniprot_id > su2.uniprot_id;
                '''.format(nodes,nodes))        
            cyEdges_raw_self = Stringinteractions.objects.raw('''
                SELECT i.id, i.prot1 AS p1, i.prot2 AS p2, i.type, 
                        i.PDB_id, 'y' as self
                FROM Interactome3d as i
                WHERE i.prot1 in {} AND i.prot2 in {} AND i.prot1 = i.prot2;
                '''.format(nodes,nodes))
            cyEdges_json = raw_to_json(cyEdges_raw, cyEdges_raw_self)
        else:
            cyEdges_json = None

        # Change cyNodes content (add interface info) when a variant is specified
        if query_var and len(nodes) > 1: 
            cyNodes_raw = Basicinfo2.objects.raw('''
            SELECT id, uniprot_id, protein_link, protein_name, gene_name, pos
            FROM (
                SELECT * 
                FROM BasicInfo2 WHERE uniprot_id in {}
                ) t1
            LEFT JOIN (
                SELECT uniprot_p2 AS uniprot_p2, GROUP_CONCAT(pos_p2,aa_p2 SEPARATOR ', ') AS pos
                FROM InteractionSurfaceFinal
                WHERE uniprot_p1 = %s AND uniprot_p2 in {}
                AND pos_p1 = %s
                GROUP BY uniprot_p2
                ) t2
            ON t1.uniprot_id = t2.uniprot_p2;
            '''.format(nodes,nodes),[query_uni,query_var])

        cyNodes_json = raw_to_json(cyNodes_raw)

        context = {
            'query': query,            
            'query_uni': query_uni,
            'query_var': query_var,
            'query_sco': query_sco,
            'query_lim': query_lim,
            'results_basic': results_basic,
            'cyNodes_json': cyNodes_json,
            'cyEdges_json': cyEdges_json,
            'nodes_len': len(nodes),
            'results_protein' : results_protein, 
            'results_gene': results_gene, 
            'results_signal' : results_signal,
            'results_signal_var' : results_signal_var,
            'trans_dom_var' : trans_dom_var,
            'tm_results' : tm_results, 
            'results_topo': results_topo,
            'results_loc_cellcomp' : results_loc_cellcomp, 
            'results_loc_topolabel': results_loc_topolabel,
            'results_variant': results_variant,
            'results_binding': results_binding, 
            'results_PTM': results_PTM,
            'Pfam_results' : Pfam_results,
            'Pfam_results_general': Pfam_results_general,
            'results_sequence': results_sequence,
            'function_results': function_results,
            'topo1_results' : topo1_results ,
            'bind1_results': bind1_results,
            'ptm1_results': ptm1_results,

m3di/templates/m3di/base.html
{% load static %}

<!DOCTYPE html>

<html>
  <head> 
    {% block Title %} {% endblock %}
    <!--Font Awesome kit's code-->
    <script src="https://kit.fontawesome.com/777bbb3675.js" crossorigin="anonymous"></script>
    <!--Link CSS stylesheet-->
    <link rel="stylesheet" href="{% static 'm3di/styles.css' %}" />
    <!--Import JQuery library -->
    <script src="https://code.jquery.com/jquery-2.0.3.min.js"></script>
    <!--Load cytoscape.js -->
    <script src="{% static 'm3di/cytoscape.js' %}"></script>
  </head>

  <div id="stick-to-top">
      <div class="top_bar">
        <div class="container"></div>
      </div>
      <header class="main-header">
        <div class="container">
          <a id="m3di_logo_left" href="{% url 'm3di:index' %}">
            <img src="{% static 'm3di/images/logo.png' %}" width="100"></a>
          <nav class="main-nav">            
            <ul>
              <li><a href="{% url 'm3di:index' %}">Home</a></li>
              <li><a href="{% url 'm3di:doc' %}">Documentation</a></li>
              <li><a href="{% url 'm3di:stats' %}">Statistics</a></li>
              <li><a href="{% url 'm3di:contact' %}">Contact us</a></li>
            </ul>
          </nav>
        </div>      
      </header>
      {% block searchBar %} {% endblock %}
  </div>

  {% block Content %} {% endblock %}

  <footer>
    <div class="container">
      <span id="msc_left">MSc Bioinformatics and Systems Biology</span>
      <img id="ic_logo_right" src="{% static 'm3di/images/Imperial.png' %}" width="200">
    </div>
  </footer>


    <script src="{% static 'm3di/scripts.js' %}"></script>


</html>

m3di/templates/m3di/contact.html
{% extends "m3di/parent.html" %}

{% block Title %}
  <title>M3DI | Contact</title>
{% endblock %}

{% block Content %}
<body>
    
</body>
{% endblock %}

m3di/templates/m3di/doc.html
{% extends "m3di/parent.html" %}

{% block Title %}
  <title>M3DI | Documentation</title>
{% endblock %}

{% block Content %}
<body>


    <hr color="#CAC4D7">
</body>
{% endblock %}

m3di/templates/m3di/index.html
{% extends "m3di/base.html" %}

{% block Title %}
  <title>M3DI | Home</title>
  <meta name="description" content="Welcome to Missense3D-Interaction">
{% endblock %}

    
{% block Content %}
<body>
  <section class="hero">
      <div class="container">
        <h1 id="welcome"> Welcome to M3DI</h1>
        <p>
            Missense 3D interaction is a database integrating data from UniProt, 
            Missense3D, String and Interactome-3D to provide the user with a tool 
            to analyse the impact of missense variants on protein-protein interactions.
        </p>
        <br>
        <a href="#home-search">
        <button type="button">Start your search</button></a>  
      </div>
    </section>

  <section id="home-search" class="home-search">
      <div class="container">

      <form id="form" action="{% url 'm3di:main' %}" method="get">
        <table>
          <tr>
            <td></td>
            <td class="left" id="example">
              <a id="example" onclick="populateInput('P31947','226')">Example: P31947, 226</a>
            </td>
          </tr>
            <tr>
              <td class="right">
                <i class="fa-solid fa-circle-info" id="fa-uni"></i>
                <div class="info-box" id="info-uni">Required*: the UniProt or Gene ID of your protein</div>
                <label>UniProt ID/Gene ID*:</label></td>
              <td class="left">
                <input id="input_uni" name="q" type="text" placeholder="e.g. Q9BYF1 or ACE2" size="18px">
                <!-- <i class="fa-solid fa-circle-info"></i> -->
              </td>
            </tr>
          <tr>
            <td class="right">
              <i class="fa-solid fa-circle-info" id="fa-var"></i>
              <div class="info-box" id="info-var">
                Optional: the UniProt position of a particular amino acid substitution in your protein</div>
              <label>Residue Position:</label></td>
            <td class="left">
              <input id="input_var" name="v" type="text" placeholder="e.g. 199"  size="10px">
            </td>
          </tr>
          <tr class="advanced-settings" style="display:none">
            <td class="right">
              <i class="fa-solid fa-circle-info" id="fa-sco"></i>
              <div class="info-box" id="info-sco">
                Optional: the minimum required score (based on experimenal evidence) to filter interactions</div>
              <label>Interaction confidence:</label></td>
            <td class="left">
              <select name="s" id="select-sco" onchange="showCustom('select-sco','input_sco')">
                <option value="0.7">High (&ge; 0.7)</option>
                <option value="0.5" selected="selected">Medium (&ge; 0.5)</option>
                <option value="0.2">Low (&ge; 0.2)</option>
                <option value="0">No Limit (&ge; 0)</option>
                <option value="Custom">Custom</option>
              </select>
              <input id="input_sco" name="s_custom" type="number" value="0.5" 
              min="0" max="1" step="0.1" style="width: 4em; visibility: hidden;">
            </td>
          </tr>
          <tr class="advanced-settings" style="display:none">
            <td class="right">
              <i class="fa-solid fa-circle-info" id="fa-lim"></i>
              <div class="info-box" id="info-lim">
                Optional: the maximum number of interactors to show</div>
              <label>Max number of interactors:</label></td>
            <td class="left">
              <select name="l" id="select-lim" onchange="showCustom('select-lim','input_lim')">
                <option value="10" selected="selected">10 interactors</option>
                <option value="20">20 interactors</option>
                <option value="50">50 interactors</option>
                <option value="100">Show All</option>
                <option value="Custom">Custom</option>                  
              </select>
              <input id="input_lim" name="l_custom" type="number" value="10"  
              min="1" max="100" style="width: 4em; visibility: hidden;" >
            </td>
          </tr>
          <tr>
            <td class="right">
              <span id="toggle-advance" onclick="toggleAdvance()">Show Advanced</span> </td>
            <td class="left">
                <button type="submit">Submit</button>
            </td>
          </tr>
        </table>
      </form>

    </div>
  </section>

    

  <section class="home-detail">
    <div class="container">
    </div>
  </section>

    <!-- <hr color="#CAC4D7"> -->
</body>
{% endblock %}

m3di/templates/m3di/stats.html
{% extends "m3di/parent.html" %}

{% block Title %}
  <title>M3DI | Statistics</title>
{% endblock %}

{% block Content %}
<body>
    
</body>
{% endblock %}